version: '3'
services:
  bouter:
    build:
      context: ./
      target: dev
    container_name: bouter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - NODE_ENV=development
      - HOST_IP=192.168.1.44
      - REDIS_HOST=192.168.1.44
      - REDIS_PORT=6379
      - MASTER_HOST=192.168.1.44
      - LOG_LEVEL=debug
      - SLAVE=false
      - TZ=Europe/Istanbul
    restart: always